-- INSERT INTO groups values (1,'Antenas');
-- INSERT INTO groups values (2,'Telecom');
UPDATE groups set name = 'Servicos' where id = 1; 
UPDATE groups set name = 'Servicos de Redes' where id = 2;
INSERT INTO groups values (3,'Informaticas');
INSERT INTO groups values (4,'Antenas KU e Digital HD');
INSERT INTO groups values (5,'CFTVs');
INSERT INTO groups values (6,'Perifericos');
INSERT INTO groups values (7,'Insumos');
INSERT INTO groups values (8,'Armazenamentos');
INSERT INTO groups values (9,'Softwares');
INSERT INTO groups values (10,'Serviços TI');
INSERT INTO groups values (11,'Componentes');
INSERT INTO groups values (12,'Cloud');
INSERT INTO groups values (13,'Licenças');
INSERT INTO groups values (14,'Hardware');
INSERT INTO groups values (15,'Fibra Optica');
INSERT INTO groups values (16,'Antenas PPP');
INSERT INTO groups values (17,'Cabos');
INSERT INTO groups values (18,'Audio e Video');
INSERT INTO groups values (19,'Roteadores');

-- insert into sub_groups values (1,'Antena Digital');
UPDATE sub_groups SET name = 'Serviço Externo', group_id = 1 where id = 1;
insert into sub_groups values (2,'Servico Interno', 1);
insert into sub_groups values (3,'Servico e Insumo', 2);
insert into sub_groups values (4,'Cabeamento e Insumo', 2);
insert into sub_groups values (5,'Manutenção', 3);
insert into sub_groups values (6,'Kit Ant Sat', 4);
insert into sub_groups values (7,'Receptor Sat', 4);
insert into sub_groups values (8,'LNBF Univ', 4);
insert into sub_groups values (9,'Cabo Parabol', 17);
insert into sub_groups values (10,'Cameras', 5);
insert into sub_groups values (11,'DVRs', 5);
insert into sub_groups values (12,'Cabo CFTV', 17);
insert into sub_groups values (13,'Mouse', 6);
insert into sub_groups values (14,'Teclado', 6);
insert into sub_groups values (15,'Suporte TV', 18);
insert into sub_groups values (16,'Cabo HDMI', 7);
insert into sub_groups values (17,'Roteador Wirelles', 19);
insert into sub_groups values (18,'Filtro de linha', 7);
insert into sub_groups values (19,'Estabilizadores', 6);
