INSERT INTO taxation_tables (
    id, fcp_uf_dest_perc, cod_benef_fiscal, code_trib_issqn,
    cofins_aliq, cofins_base, cs_aliq, cs_base,
    cst_cofins, cst_issqn_pref, cst_pis, cst_ipi,
    fcp_uf_dest_base, fcp_uf_dest_base_st, fcp_uf_dest_perc_st,
    icms_aliq, icms_aliq_interestadual, icms_aliq_st, icms_aliq_uf_dest,
    icms_base, icms_diferido, icms_margem_st, icms_mod_bc,
    icms_obs, icms_st_tributado, icms_trib, icms_usa_margem_st,
    ipi_aliq, ipi_unit, ir_aliq, ir_base,
    iss_aliq, iss_base, name, natureza_receita_pis_cofins,
    pis_base, sf_base, sf_aliq, st_mod_bc
)
VALUES (
    1,
    0,
    1,
    'N',
    12,
    90,
    12,
    100,
    2,
    1,
    1,
    1,
    12,
    12,
    12,
    12,
    12,
    12,
    12,
    12,
    12,
    12,
    1,
    'ss',
    1,
    1,
    1,
    1,
    'n',
    1,
    12,
    12,
    90,
    'Mercadoria Tributada Normalmente',
    1,
    12,
    12,
    12,
    1
);